#! /bin/sh

setxkbmap be
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#66ACED"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# feh --bg-scale --randomize "$HOME/Pictures/Wallpapers/rotation/*" 
# feh --bg-scale "$(find $HOME/Pictures/Wallpapers/rotation -type f | shuf -n 1)" &
# feh --bg-center ~/Pictures/Wallpapers/copland-big-ascii.png &

polybar &

picom -b &

xinput set-prop 11 'libinput Natural Scrolling Enabled' 1 &

xinput set-prop 11 'libinput Tapping Enabled' 1 &


# ./xinputshit.sh &
